//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 02:35:27 PM CET 
//


package eu.fbk.dkm.premon.premonitor.verbnet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DESCRIPTION")
public class DESCRIPTION {

    @XmlAttribute(name = "primary", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primary;
    @XmlAttribute(name = "secondary")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String secondary;
    @XmlAttribute(name = "descriptionNumber", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String descriptionNumber;
    @XmlAttribute(name = "xtag", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xtag;

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimary(String value) {
        this.primary = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondary() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondary(String value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the descriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionNumber() {
        return descriptionNumber;
    }

    /**
     * Sets the value of the descriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionNumber(String value) {
        this.descriptionNumber = value;
    }

    /**
     * Gets the value of the xtag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXtag() {
        return xtag;
    }

    /**
     * Sets the value of the xtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXtag(String value) {
        this.xtag = value;
    }

}
