//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 02:35:27 PM CET 
//


package eu.fbk.dkm.premon.premonitor.verbnet;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.dkm.premon.premonitor.verbnet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.dkm.premon.premonitor.verbnet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NP }
     * 
     */
    public NP createNP() {
        return new NP();
    }

    /**
     * Create an instance of {@link SYNRESTRS }
     * 
     */
    public SYNRESTRS createSYNRESTRS() {
        return new SYNRESTRS();
    }

    /**
     * Create an instance of {@link SELRESTRS }
     * 
     */
    public SELRESTRS createSELRESTRS() {
        return new SELRESTRS();
    }

    /**
     * Create an instance of {@link SYNRESTR }
     * 
     */
    public SYNRESTR createSYNRESTR() {
        return new SYNRESTR();
    }

    /**
     * Create an instance of {@link ARGS }
     * 
     */
    public ARGS createARGS() {
        return new ARGS();
    }

    /**
     * Create an instance of {@link ARG }
     * 
     */
    public ARG createARG() {
        return new ARG();
    }

    /**
     * Create an instance of {@link PRED }
     * 
     */
    public PRED createPRED() {
        return new PRED();
    }

    /**
     * Create an instance of {@link ADJ }
     * 
     */
    public ADJ createADJ() {
        return new ADJ();
    }

    /**
     * Create an instance of {@link PREP }
     * 
     */
    public PREP createPREP() {
        return new PREP();
    }

    /**
     * Create an instance of {@link FRAME }
     * 
     */
    public FRAME createFRAME() {
        return new FRAME();
    }

    /**
     * Create an instance of {@link DESCRIPTION }
     * 
     */
    public DESCRIPTION createDESCRIPTION() {
        return new DESCRIPTION();
    }

    /**
     * Create an instance of {@link EXAMPLES }
     * 
     */
    public EXAMPLES createEXAMPLES() {
        return new EXAMPLES();
    }

    /**
     * Create an instance of {@link SYNTAX }
     * 
     */
    public SYNTAX createSYNTAX() {
        return new SYNTAX();
    }

    /**
     * Create an instance of {@link SEMANTICS }
     * 
     */
    public SEMANTICS createSEMANTICS() {
        return new SEMANTICS();
    }

    /**
     * Create an instance of {@link VERB }
     * 
     */
    public VERB createVERB() {
        return new VERB();
    }

    /**
     * Create an instance of {@link ADV }
     * 
     */
    public ADV createADV() {
        return new ADV();
    }

    /**
     * Create an instance of {@link LEX }
     * 
     */
    public LEX createLEX() {
        return new LEX();
    }

    /**
     * Create an instance of {@link MEMBER }
     * 
     */
    public MEMBER createMEMBER() {
        return new MEMBER();
    }

    /**
     * Create an instance of {@link SELRESTR }
     * 
     */
    public SELRESTR createSELRESTR() {
        return new SELRESTR();
    }

    /**
     * Create an instance of {@link THEMROLE }
     * 
     */
    public THEMROLE createTHEMROLE() {
        return new THEMROLE();
    }

    /**
     * Create an instance of {@link VNSUBCLASS }
     * 
     */
    public VNSUBCLASS createVNSUBCLASS() {
        return new VNSUBCLASS();
    }

    /**
     * Create an instance of {@link MEMBERS }
     * 
     */
    public MEMBERS createMEMBERS() {
        return new MEMBERS();
    }

    /**
     * Create an instance of {@link THEMROLES }
     * 
     */
    public THEMROLES createTHEMROLES() {
        return new THEMROLES();
    }

    /**
     * Create an instance of {@link FRAMES }
     * 
     */
    public FRAMES createFRAMES() {
        return new FRAMES();
    }

    /**
     * Create an instance of {@link SUBCLASSES }
     * 
     */
    public SUBCLASSES createSUBCLASSES() {
        return new SUBCLASSES();
    }

    /**
     * Create an instance of {@link VNCLASS }
     * 
     */
    public VNCLASS createVNCLASS() {
        return new VNCLASS();
    }

    /**
     * Create an instance of {@link EXAMPLE }
     * 
     */
    public EXAMPLE createEXAMPLE() {
        return new EXAMPLE();
    }

}
