//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 02:35:27 PM CET 
//


package eu.fbk.dkm.premon.premonitor.verbnet;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "selrestrOrSELRESTRS"
})
@XmlRootElement(name = "SELRESTRS")
public class SELRESTRS {

    @XmlAttribute(name = "logic")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String logic;
    @XmlElements({
        @XmlElement(name = "SELRESTR", type = SELRESTR.class),
        @XmlElement(name = "SELRESTRS", type = SELRESTRS.class)
    })
    protected List<Object> selrestrOrSELRESTRS;

    /**
     * Gets the value of the logic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogic() {
        return logic;
    }

    /**
     * Sets the value of the logic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogic(String value) {
        this.logic = value;
    }

    /**
     * Gets the value of the selrestrOrSELRESTRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selrestrOrSELRESTRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSELRESTROrSELRESTRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SELRESTR }
     * {@link SELRESTRS }
     * 
     * 
     */
    public List<Object> getSELRESTROrSELRESTRS() {
        if (selrestrOrSELRESTRS == null) {
            selrestrOrSELRESTRS = new ArrayList<Object>();
        }
        return this.selrestrOrSELRESTRS;
    }

}
