//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 02:35:27 PM CET 
//


package eu.fbk.dkm.premon.premonitor.verbnet;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "npOrVERBOrADJOrADVOrPREPOrLEX"
})
@XmlRootElement(name = "SYNTAX")
public class SYNTAX {

    @XmlElements({
        @XmlElement(name = "NP", required = true, type = NP.class),
        @XmlElement(name = "VERB", required = true, type = VERB.class),
        @XmlElement(name = "ADJ", required = true, type = ADJ.class),
        @XmlElement(name = "ADV", required = true, type = ADV.class),
        @XmlElement(name = "PREP", required = true, type = PREP.class),
        @XmlElement(name = "LEX", required = true, type = LEX.class)
    })
    protected List<Object> npOrVERBOrADJOrADVOrPREPOrLEX;

    /**
     * Gets the value of the npOrVERBOrADJOrADVOrPREPOrLEX property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npOrVERBOrADJOrADVOrPREPOrLEX property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNPOrVERBOrADJOrADVOrPREPOrLEX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NP }
     * {@link VERB }
     * {@link ADJ }
     * {@link ADV }
     * {@link PREP }
     * {@link LEX }
     * 
     * 
     */
    public List<Object> getNPOrVERBOrADJOrADVOrPREPOrLEX() {
        if (npOrVERBOrADJOrADVOrPREPOrLEX == null) {
            npOrVERBOrADJOrADVOrPREPOrLEX = new ArrayList<Object>();
        }
        return this.npOrVERBOrADJOrADVOrPREPOrLEX;
    }

}
